### ISSUE TITLE
Dependency on babel-runtime

### ISSUE THREAD

**Issue by pwagener** [JFusco/es6-event-emitter#3]
Attempting to use `es6-event-emitter` without `babel-runtime` as a direct dependency results in this error:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'babel-runtime/helpers/classCallCheck'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/pwagener/Devel/callbacks/node_modules/es6-event-emitter/dist/emitter.js:7:24)
    at Module._compile (module.js:409:26)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pwagener/Devel/callbacks/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
   ...
```

Adding `babel-runtime` as a direct dependency of my project seems to resolve it.

**Comment by JFusco** [comment]
Hey @pwagener - thanks for pointing this out. We actually don't even need `babel-runtime`. I removed it as a dependency from the `package.json` file in the latest patch. v1.5.2

I tested it by re-compiling and publishing to NPM..Pulling the new package down in to a regular es6 project - it's emitting properly with no errors.

Let me know if you still have issues when you remove `babel-runtime` from your project. I'll keep this issue open until you can confirm for me.

**Comment by Wkasel** [comment]
Still an issue, see #8.
